### PR TITLE
fix: root level assignments are properly explained in the proof when logging inferences

### LINKED ISSUE #118: LessThanOrEqual propagator exception
Hi,

I'm using the Python interface to generate some proof logs, but when trying to solve the model below, I get an assertion error thrown by a the `leq` propagator.

```
thread '<unnamed>' panicked at /home/ignace/git/Pumpkin/pumpkin-solver/src/propagators/arithmetic/linear_less_or_equal.rs:114:9:
propagator should only be triggered when lower bounds are tightened, old_bound=1, new_bound=1
```

```python
from pumpkin_py import Model, constraints

model = Model()

iv = model.new_integer_variable(0,1)
a = model.new_boolean_variable(name="a")
b = model.new_boolean_variable(name="b")
c = model.new_boolean_variable(name="c")

model.add_constraint(constraints.Clause([a, b]))          # a \/ b
model.add_constraint(constraints.Clause([b.negate(),c]))  # b -> c
model.add_constraint(constraints.Clause([model.predicate_as_boolean(iv, Comparator.Equal, 1)])) # iv == 1
model.add_implication(constraints.Equals([iv], 0), c)  # c -> iv == 0

model.satisfy(proof="test")
```

### LINKED ISSUE #119: Index-error during clause-allocation
Hi,

Potentially related to #118 (I encountered this case when minimizing an example for that issue).

I have the following piece of code for generating an UNSAT model:
```python
from pumpkin_py import Model, constraints, Comparator

n = 3    
model = Model()

bvs = [model.new_boolean_variable(name=f"BV{i})") for i in range(n)]
ivs = [model.new_integer_variable(0,1,name=f"IV{i}") for i in range(n)]

neg_scaled = [model.boolean_as_integer(b).scaled(-1) for b in bvs]
model.add_constraint(constraints.LessThanOrEquals(neg_scaled, -1))

for i in range(n):
    is_0 = model.predicate_as_boolean(ivs[i], Comparator.Equal, 0)
    is_1 = model.predicate_as_boolean(ivs[i], Comparator.Equal, 1)

    model.add_constraint(constraints.Clause([is_1]))
    model.add_implication(constraints.Clause([is_0]), bvs[i])

model.satisfy(proof="test")
```

This raises the error 
```
thread '<unnamed>' panicked at pumpkin-solver/src/engine/sat/clause_allocators/clause_allocator_basic.rs:52:32:
index out of bounds: the len is 0 but the index is 18446744073709551615
```

I did a little investigation already, and the model runs fine when putting the constaint "sum(bvs) >= 1" all the way at the end of the model.

Feel free to close this issue if the root cause is the same as #118  : )

### LINKED ISSUE #156: Entered Unreachable code in proof-logging
Hi,

I'm trying to find a proof-log of an unsatisfiable Sudoku model.
When solving without proof-logging, the solver concludes correctly that the model is UNSAT.
However, when enabling proof-logging, I get the following error:

```bash
thread '<unnamed>' panicked at pumpkin-solver/src/engine/constraint_satisfaction_solver.rs:1320:21:
internal error: entered unreachable code
stack backtrace:
0: rust_begin_unwind
         at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/std/src/panicking.rs:665:5
1: core::panicking::panic_fmt
         at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/panicking.rs:76:14
2: core::panicking::panic
         at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/panicking.rs:148:5
3: pumpkin_solver::engine::constraint_satisfaction_solver::ConstraintSatisfactionSolver::log_root_propagation_to_proof
         at /home/ignace/git/Pumpkin/pumpkin-solver/src/engine/constraint_satisfaction_solver.rs:1320:21
4: pumpkin_solver::engine::constraint_satisfaction_solver::ConstraintSatisfactionSolver::propagate
         at /home/ignace/git/Pumpkin/pumpkin-solver/src/engine/constraint_satisfaction_solver.rs:1180:17
5: pumpkin_solver::engine::constraint_satisfaction_solver::ConstraintSatisfactionSolver::solve_internal
         at /home/ignace/git/Pumpkin/pumpkin-solver/src/engine/constraint_satisfaction_solver.rs:770:13
6: pumpkin_solver::engine::constraint_satisfaction_solver::ConstraintSatisfactionSolver::solve_under_assumptions
         at /home/ignace/git/Pumpkin/pumpkin-solver/src/engine/constraint_satisfaction_solver.rs:471:22
7: pumpkin_solver::engine::constraint_satisfaction_solver::ConstraintSatisfactionSolver::solve
         at /home/ignace/git/Pumpkin/pumpkin-solver/src/engine/constraint_satisfaction_solver.rs:455:9
8: pumpkin_solver::api::solver::Solver::satisfy
         at /home/ignace/git/Pumpkin/pumpkin-solver/src/api/solver.rs:311:15
9: pumpkin_py::model::Model::satisfy
         at /home/ignace/git/Pumpkin/pumpkin-py/src/model.rs:163:15
10: pumpkin_py::model::Model::__pymethod_satisfy__
         at /home/ignace/git/Pumpkin/pumpkin-py/src/model.rs:41:1
```

Full model (in Python) below - I'm currently running on the `develop` branch (commit `94e76035`)
```python
import pumpkin_py as pm
from pumpkin_py import constraints
import numpy as np

givens = np.array([[0, 0, 0, 0, 7, 0, 2, 0, 6],
                    [0, 0, 0, 0, 0, 0, 4, 0, 1],
                    [0, 0, 2, 0, 8, 0, 0, 0, 0],
                    [0, 0, 6, 0, 0, 5, 0, 0, 8],
                    [7, 0, 0, 2, 0, 0, 5, 9, 0],
                    [0, 0, 9, 0, 4, 8, 0, 0, 0],
                    [0, 5, 0, 0, 9, 6, 8, 0, 2],
                    [0, 2, 0, 8, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 2, 0, 0, 6, 0]])


model = pm.Model()

cells = np.array([[model.new_integer_variable(1,9, f"cell{[i,j]}") for i in range(9)] for j in range(9)])

# Row constraints
for row in cells:
    model.add_constraint(constraints.AllDifferent(row.tolist()))

# Column constraints
for col in cells.T:
    model.add_constraint(constraints.AllDifferent(col.tolist()))

# Block constraints
for i in range(0,9,3):
    for j in range(0,9,3):
        block = cells[i:i+3, j:j+3]
        model.add_constraint(constraints.AllDifferent(list(block.flat)))

# set given values
for i in range(9):
    for j in range(9):
        if givens[i,j] != 0:
            model.add_constraint(constraints.Equals([cells[i,j]], givens[i,j]))


print("Solving without prooflog")
print(model.satisfy())


print("Solving with prooflog")
print(model.satisfy(proof="proof"))
```

### PR DESCRIPTION
**Pull request by maartenflippo**
Closes #118
Closes #119
Closes #156

### CODE REVIEW

File: pumpkin-solver/src/proof/finalizer.rs [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+pub(crate) struct FinalizingContext<'a> {
+    pub(crate) conflict: PropositionalConjunction,
+    pub(crate) propagators: &'a mut PropagatorStore,
+    pub(crate) proof_log: &'a mut ProofLog,
+    pub(crate) unit_nogood_step_ids: &'a HashMap<Predicate, StepId>,
+    pub(crate) assignments: &'a Assignments,
+    pub(crate) reason_store: &'a mut ReasonStore,
+}
+
+pub(crate) fn finalize_proof(context: FinalizingContext<'_>) {
```
Comment (ImkoMarijnissen) [inline pumpkin-solver/src/proof/finalizer.rs:26]: Documentation please

File: pumpkin-solver/src/proof/proof_literals.rs [hunk 2]
```diff
@@ -36,6 +44,53 @@ impl ProofLiterals {
...
+        // Note: This only works because we assume `literal` is a fresh literal and we are given
+        // the positive polarity. That assumption holds as the only place this can be called is
+        // transitively through `new_literal_for_predicate`. As soon as this assumption is
+        // violated, all hell will break loose.
+        let domain = literal.get_true_predicate().get_domain();
+
+        let _ = self.reification_domains.insert(domain, predicate);
+    }
+
+    fn get_underlying_predicate(&self, predicate: Predicate) -> Option<Predicate> {
```
Comment (ImkoMarijnissen) [inline pumpkin-solver/src/proof/proof_literals.rs:58]: Documentation please

**Review by ImkoMarijnissen — CHANGES_REQUESTED** [review]

File: pumpkin-solver/src/engine/constraint_satisfaction_solver.rs [hunk 3]
```diff
@@ -1449,13 +1442,19 @@ impl ConstraintSatisfactionSolver {
...
+            self.prepare_for_conflict_resolution();
+            self.complete_proof();
             Err(ConstraintOperationError::InfeasibleState)
         } else {
             Ok(())
         }
     }
 
     fn prepare_for_conflict_resolution(&mut self) {
+        if self.state.is_conflicting() {
```
[the remark this answers is not in the document]
Comment (maartenflippo) [reply pumpkin-solver/src/engine/constraint_satisfaction_solver.rs:1452]: We get here when `EmptyDomain` is triggered in a propagator. It just happens that the proof explaining also requires that state. So it is fine.

File: pumpkin-solver/src/engine/conflict_analysis/conflict_analysis_context.rs [hunk 4]
```diff
@@ -47,7 +47,6 @@ pub(crate) struct ConflictAnalysisContext<'a> {
     pub(crate) proof_log: &'a mut ProofLog,
     pub(crate) should_minimise: bool,
 
-    pub(crate) is_completing_proof: bool,
     pub(crate) unit_nogood_step_ids: &'a HashMap<Predicate, StepId>,
```
Comment (ImkoMarijnissen) [inline pumpkin-solver/src/engine/conflict_analysis/conflict_analysis_context.rs:50]: Do we still need the unit_nogood_step_ids in this case?

File: pumpkin-solver/src/engine/conflict_analysis/resolvers/resolution_resolver.rs [hunk 5]
```diff
@@ -157,10 +153,6 @@ impl ConflictResolver for ResolutionResolver {
                         );
 
                         if self.reason_buffer.is_empty() {
-                            // In the case when the proof is being completed, it could be the case
```
Comment (ImkoMarijnissen) [inline pumpkin-solver/src/engine/conflict_analysis/resolvers/resolution_resolver.rs:160]: This should now never be the case, please add a panic!

**Review by ImkoMarijnissen — CHANGES_REQUESTED** [review]

File: pumpkin-solver/src/engine/constraint_satisfaction_solver.rs [hunk 6]
```diff
@@ -740,6 +738,8 @@ impl ConstraintSatisfactionSolver {
                 &mut self.stateful_assignments,
             );
             self.state.declare_ready();
+        } else {
+            self.state.declare_infeasible();
```
[the remark this answers is not in the document]
Comment (ImkoMarijnissen) [reply pumpkin-solver/src/engine/constraint_satisfaction_solver.rs]: I see that this has been removed entirely, what is the reasoning?

**Review by ImkoMarijnissen — APPROVED** [review]
